### ISSUE TITLE
manifest 오류

### ISSUE THREAD

**Issue by 4z7l** [team-MonoPad/MonoPad#10]
Expecting \<uses-feature android:name="android.software.leanback" android:required="false" /\> tag. 

Expecting an activity to have android.intent.category.LEANBACK_LAUNCHER intent filter. 

Hardware feature android.hardware.touchscreen not explicitly marked as optional 

오류 뜸.

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.project.monopad">

    <uses-feature
        android:name="android.software.leanback"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.touchscreen"
        android:required="false" />

    <uses-permission android:name="android.permission.INTERNET"/>

    <application
```

이렇게 하면 빌드가 되긴하지만 여전히 manifest에 빨간줄 뜸.. 왤까요..?

**Comment by 4z7l** [comment]
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.project.monopad"
    tools:ignore="ImpliedTouchscreenHardware,MissingLeanbackLauncher,MissingLeanbackSupport">
```

이렇게 tools:ignore를 추가하니 빨간줄 안뜨고 되긴함.. 근데 왜 뜨는 오류일까요

**Comment by Haeseong5** [comment]
데스크탑에서도 동일하게 에러나오나요?
검색해보니 안드로이드TV를 지원하는 앱으로 설정이 된 것 같네요. menifest 아래 쪽에 관련 태그가 붙은게 아닐까요?

아래처럼 leanback 이라는 태그가 붙어서 그럴 수도 있을 것 같네요. 

<intent-filter>
  <action android:name="android.intent.action.MAIN" />
  <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
</intent-filter>

    <activity android:name=".xxx.activity.SplashActivity">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
            <category android:name="android.intent.category.**LEANBACK_LAUNCHER**" />
        </intent-filter>
    </activity>

**Comment by 4z7l** [comment]
### 오류나는 코드 전체
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.project.monopad"
    >

    <uses-permission android:name="android.permission.INTERNET"/>

    <application
        android:name=".MonoApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".ui.view.MainActivity"/>
        <activity android:name=".ui.view.RegisterActivity"/>
        <activity android:name=".ui.view.LoginActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```


> `tools:ignore="ImpliedTouchscreenHardware,MissingLeanbackLauncher,MissingLeanbackSupport"` 붙였을 때에는 정상작동함

**Comment by 4z7l** [comment]
# 해결 방법

- build.gradle(Module:app)에 추가한
`implementation 'com.jakewharton.rxbinding4:rxbinding-leanback:4.0.0'` 때문이었음..
지우니 정상작동함
