### ISSUE TITLE
[debug] 리뷰 저장 후 캘린더에 바로 반영이 안되는 현상

### ISSUE THREAD

**Issue by DevHyeonseong** [team-MonoPad/MonoPad#102]
#### 문제 
home / search -> detail -> edit  를 통해서 작성한 리뷰가 캘린더에 바로 반영 안되고 어플 재접속 해야 반영됨

#### 원인 예상
1. 프래그먼트 트랜잭션을 사용해서 탭간 이동시 그 전 데이터가 유지되서 그런 것으로 판단. 슬기님이 다이어리 코드에서 onResume에서 데이터를 최신화 해주시는데.. home / search에서 저장할 경우 DB에는 저장이 되지만 화면을 구성하는 데이터가 이전 상태 bundle로 유지되서 그런거 같은데.. 그래서 재접속 하면 잘 떠요. 확인해서 고쳐주세요!

**Comment by 4z7l** [comment]
ac486d3

- DiaryDao에 getAllReview를 Livedata 형식으로 반환하는 부분 추가
-> 왜인진 모르겠으나 이렇게 하니 해결이 됨.. 
-> onResume에서 업데이트 하지 않아도 알아서 잘 반영되어 onresume에서 data 다시 가져오는 코드 삭제
-> 의문의 해결을 했으므로 저도 더 찾아보겠습니다..

- 기존의 `fun getAllReview() : Single<List<Review>>`를 빼려했으나 [**DetailViewModel**](https://github.com/team-MonoPad/MonoPad/blob/95685b693da486d5b25e904847a585987773acbd/app/src/main/java/com/project/monopad/ui/viewmodel/DetailViewModel.kt#L138)에서 참조하고 있어서 그냥 둠

https://github.com/team-MonoPad/MonoPad/commit/9336574d1ebc3568c828e2293aed9693e8bd0134#r44099253
코멘트 남겼는데 봐주세요
