### ISSUE TITLE
firebase 연동하여 로그인,회원가입 구현

### ISSUE THREAD

**Issue by 4z7l** [team-MonoPad/MonoPad#2]
- [x] firebase 연동

- [x] 로그인 구현 bf1450d 
 + MVVM 기반 로그인 로직 구현을 하긴했지만.. 너무 어려워요.....ㅠㅠ진심 8시간 정도 걸림; 
 + 이메일,비밀번호 유효한지 확인
 + 로그인시 사용자의 uid, 이메일을 `AuthRepository`에 저장
 + 임의로 aa@aa.aa / aaaaaa 계정 만들어둠
 + 로그인 시 mainactivity로 이동

- [x] 회원가입 0bcfb26

> - [x] 이메일 중복체크
> - [x] 자동로그인
> - [x] progressdialog

- [x] 패키지 수정 -> merge 후 할 예정  3847645

- [x] di, rx, base 적용 3b8211c

> rxbinding -> 적용하려면 여러 문제가 있어서 더 고민해봐야할듯..

**Comment by 4z7l** [comment]
https://muhammadfawzy.github.io/posts/2018/08/mvvm-livedata-koltin/

**Comment by 4z7l** [comment]
https://github.com/umangburman/MVVM-DataBinding-With-LiveData-Login/tree/master/app/src/main/java/com/example/umangburman/databindingwithlivedata

**Comment by 4z7l** [comment]
https://umangburman.github.io/MVVM-DataBinding-With-LiveData-Login/

**Comment by jaeyunn15** [comment]
작업 완료되면 커밋 넘버를 옆에 같이 적어주세요!
ex ) [작업완료] (커밋넘버) (작업 내역 상세)
ex ) [작업완료] 2fce812s1 (MVVM기반 로그인 로직 구현 )

**Comment by 4z7l** [comment]
https://www.simplifiedcoding.net/firebase-mvvm-example/

**Comment by JeongJae-yun** [comment]
슬기님 브랜치 안 따고 master에 하셨나요..?

**Comment by jaeyunn15** [comment]
https://github.com/team-MonoPad/MonoPad/issues/2#issue-707805511 <-- 여기서보면
회원가입 먼저 하시고 HttpInterceptor는 일단 제외해요! 당장 필요하지 않을것 같으니! 궁금하시면 개념만 찾아보세요!

회원가입/로그인 완성 하시면 코드리뷰로 올려주세요!
화욜에 리뷰하고 pull/request 시킬게요!
다만 지금 구성 자체가 워낙 달라져서 conflict 우려가 있을 수 있겠네요.

**Comment by 4z7l** [comment]
https://trend21c.tistory.com/2112
https://deque.tistory.com/108

**Comment by 4z7l** [comment]
https://www.simplifiedcoding.net/firebase-mvvm-example/

**Comment by 4z7l** [comment]
https://nittaku.tistory.com/213

**Comment by 4z7l** [comment]
RxBinding import가 안됨..
gradle 추가했고 RxTextView나 RxView 같은 class나 메소드들이 import가 안됨 ㅠㅠ

**Comment by jaeyunn15** [comment]
social 로그인은 issue 다른 거로 빼서 작업해주세요. 여기는 파베 이용한 기본적 로그인/회원가입 완성되면 닫을게요
