### ISSUE TITLE
Calendar UI Setting 

### ISSUE THREAD

**Issue by jaeyunn15** [team-MonoPad/MonoPad#26]
Calendar UI Setting

**Comment by jaeyunn15** [comment]
- [X] UI SETTING 
    - ViewType별 ViewHolder구분하여 Calendar UI Set dea2458

#### Issue 사항
- TextBindingAdapter내의 메서드 static하게 유지 : @JvmStatic 형태로.

#### Ref.
- https://github.com/YunTaeSik/Calendar_IOS

#### 기타 사항
- UI set 논의 및 관련 로직 개선 가능 여부

**Comment by jaeyunn15** [comment]
- [X] Monthly Calendar UI SETTING  967d630
: 월간 달력 UI Calendar 
: 기존 IOS 형태의 달력에서 UI 변경

**Comment by 4z7l** [comment]
### UI 수정 
ada2ef0
- 다른 달의 날짜 회색으로 나오게 함
- 상단의 ㅇㅇㅇㅇ년 ㅇㅇ월 눌렀을때 DatePickerDialog 뜨도록
- 날짜 상단에 테두리 넣음
 -> padding 없이 테두리가 이어지게 하고 싶었는데 잘 안되네요.. 이어지게 하면 selector가 적용이 안됨.. 왤까..

|<img src="https://user-images.githubusercontent.com/45537782/95578367-bee08e80-0a6e-11eb-83c2-8c611bdd7881.png" width="100%">|<img src="https://user-images.githubusercontent.com/45537782/95578377-c2741580-0a6e-11eb-807d-fa25cf821938.png" width="100%">|<img src="https://user-images.githubusercontent.com/45537782/95578382-c43dd900-0a6e-11eb-858d-323d61e48a96.png" width="100%">|
|:--:|:--:|:--:|

**Comment by 4z7l** [comment]
9e6bed1

|기본|리뷰 있는 날짜 클릭시|전체 동작|
|--|--|--|
|![Screenshot_1603200855](https://user-images.githubusercontent.com/45537782/96593489-85d4d380-1324-11eb-8640-4f24bb017337.png)|![Screenshot_1603200855](https://user-images.githubusercontent.com/45537782/96593688-c0d70700-1324-11eb-8b3b-220e616b466d.png)|<img src="https://user-images.githubusercontent.com/45537782/96594079-317e2380-1325-11eb-9591-df4b40be156b.gif" width="1080px">|
