### ISSUE TITLE
BottomNavigationView+ViewPager2 / HomeFragment

### ISSUE THREAD

**Issue by Haeseong5** [team-MonoPad/MonoPad#7]
MainActivity
- [x] MainActivity - BottomNavigationView   75b7751

- [x] HomeFragment

**Comment by jaeyunn15** [comment]
해성님 아래 사진처럼 BottomNavigationView 누를때 아이콘이 나오지 않습니다.
모든 바텀 버튼들의 title과 icon이 계속 보여지게 해주세요

<img width ="300" height="500" src="https://user-images.githubusercontent.com/55985789/94584502-ae375800-02b9-11eb-8a1e-cea54e7ca463.png">

**Comment by Haeseong5** [comment]
리사이클러뷰 아이템을 하나의 xml로 통합해야 할 지

- 리사이클러뷰 별로 텍스트 및 효과를 VISIBLE, GONE 설정하는 것이 나을지 또는 별도의 아이템 레이아웃으로 분리해놓는 것이 나을지.

- gradient 필터를 적용할 때 FrameLayout을 이용하여 이미지뷰 위에 뷰를 겹치는 형식으로 해도 괜찮을지

 

xml파일에서 데이터바인딩을 이용해야 하는지.

 

ProgressBar

- 프로그레스바 show / hide 코드 어떻게 짤 지.

- 뷰모델에서 여러 싱글 중  마지막 싱글의 데이터 발행이 끝나는 시점을 어떻게 계산할 수 있을지.

 

Res 

- colors, style, dimes 등 res 파일 사용하고 있는지?

 

Toolbar

- Fragment에서 MainActivity에 있는 Toolbar를 어떻게 건드려야할지

 

Background Color

- black말고 darkGrey 색깔로 변경하는 것이 어떨지 (완전 검정색은 눈의 피로감을 더욱 높인다고함)

 
Global 하게 사용할 변수들 BaseApplication에 코드 추가해도 되는지
