### ISSUE TITLE
[Fragment] Fragment 이동간 화면 재생성 이슈

### ISSUE THREAD

**Issue by DevHyeonseong** [team-MonoPad/MonoPad#86]
## ISSUE
이슈 내용 :  Bottom Navigation을 이용하여 탭 간 이동시, 기존에 있던 화면이 유지되지 않고 view가 새로 그려지는 심각한 문제발생

- 네트워크 연결 상태 관련해서 데이터를 받아오는 부분 확인
- 기존에 있던 화면이 유지 되지 않고 새로운 화면이 그려지는 이유

## Opinion
@JeongJae-yun  
-> LiveData를 계속 감지하지 못하고 있는것 같은데...

@4z7l : 현성님이 달아놓은 링크 보니까 아예 jetpack navigation의 버그 같은데 고칠수 있나요..??
아님 MainActivity에서 ViewModel의 Data를 observe하고 fragment에서는 activity 차원에서 이미 변경이 반영된 data를 갈아끼우기만 하는 그런 로직은 구현이 안되려나요..? 어렵네여 ㅠ

@JeongJae-yun 
-> navigation이 fragment를 onCreate로 계속 불러서 생기는데 이 부분에 대해서 saveInstance가 필요하네요.
근데 jetpack navigation을 부분적으로 쓰면서 koin으로 의존성 주입을 하고 있는 상태라서 
공식 문서에는 Dagger2로 jetpack navigation save state를 지원을 해주는데 koin이라서 쉽지 않네요.

**Comment by DevHyeonseong** [comment]
https://myung6024.tistory.com/135

https://github.com/android/architecture-components-samples/issues/530

**Comment by Haeseong5** [comment]
지니뮤직앱도 바텀네비게이션뷰로 구성되어있는데 탭마다 초기화되는 방식이네요. 초기화되는 것 자체가 큰 문제라기 보단 저희가 의도하지 않은대로 나온거라면 문제일듯합니다. 

네비게이션을 안쓰는 방법으로 한다면 해결할 수 있을 듯합니다.

**Comment by jaeyunn15** [comment]
### 성능 이슈 존재
기존 jetpack bottomsheet navigation  (https://material.io/components/bottom-navigation)
-> Material Design 버전의  Bottom Navigation으로 교체 (https://material.io/components/bottom-navigation)
